version: "3.8"

services:
  media-stack:
    build: .
    container_name: media-stack
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    ports:
      - "8080:8080" # qBittorrent WebUI
      - "6881:6881" # qBittorrent TCP
      - "6881:6881/udp" # qBittorrent UDP
      - "9696:9696" # Prowlarr
      - "8989:8989" # Sonarr
      - "7878:7878" # Radarr
      - "2468:2468" # cross-seed
    volumes:
      - /docker/compose/qbittorrent/config:/config/qbittorrent
      - /docker/compose/prowlarr/config:/config/prowlarr
      - /docker/compose/sonarr/config:/config/sonarr
      - /docker/compose/radarr/config:/config/radarr
      - /docker/compose/cross-seed/config:/config/cross-seed
      - /srv/mergerfs/rust/tor:/tor
      - /srv/mergerfs/rust/caches/tor:/caches
