[supervisord]
nodaemon=true
user=root

[program:qbittorrent]
command=qbittorrent-nox --webui-port=8080 --profile=/config/qbittorrent --save-path=/tor/downloads
directory=/config/qbittorrent
user=appuser
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:prowlarr]
command=/opt/prowlarr/Prowlarr -nobrowser -data=/config/prowlarr
directory=/opt/prowlarr
user=appuser
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sonarr]
command=/opt/sonarr/Sonarr -nobrowser -data=/config/sonarr
directory=/opt/sonarr
user=appuser
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:radarr]
command=/opt/radarr/Radarr -nobrowser -data=/config/radarr
directory=/opt/radarr
user=appuser
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cross-seed]
command=cross-seed daemon --config /config/cross-seed/config.js
directory=/config/cross-seed
user=appuser
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0